My foods
========================================================

Foods that don't have a USDA entry, or need their USDA entry tweaked.  Apparent mismatches in the database for calories and fat grams is to be expected see https://www.ars.usda.gov/Main/docs.htm?docid=6233#4-9-4.
```{r Tweak}
USDAwide[Long_Desc=="Protein supplement, milk based, Muscle Milk, powder",Price:=32.99/52/35*100]
USDAwide[Long_Desc=="Protein supplement, milk based, Muscle Milk, powder",Chromium_mcg:=DRI2unit((40/35)*100,"Chromium_mcg")]
USDAwide[Long_Desc=="Nuts, pistachio nuts, dry roasted, with salt added",Price:=(19.49/(30*30))*100]
names(USDAwide[Long_Desc=="Protein supplement, milk based, Muscle Milk, powder",])
USDAwide[Long_Desc=="Kale, raw",Price:=(5.29/6.8)]
USDAwide[Long_Desc=="Broccoli, frozen, spears, unprepared",Price:=6.29/22.68]
USDAwide[Long_Desc=="Nuts, almonds, dry roasted, with salt added",Price:=13.99/11.3]
USDAwide[Long_Desc=="Yogurt, Greek, plain, nonfat",Price:=(6.89/(907*2))*100]
USDAwide[Long_Desc=="Chicken, broilers or fryers, breast, skinless, boneless, meat only, enhanced, raw",Price:=17.99/27.3]
USDAwide[Long_Desc=="Spices, paprika",Price:=2.99/2.4]
USDAwide[Long_Desc=="Spices, pepper, red or cayenne",Price:=6.99/3.96]
    
```
```{r Template}
blank.food <- structure(list(
     Long_Desc = "BLANK",
     Price = NA_real_,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = NA_real_,
    `Total lipid (fat)_g` = NA_real_,
    `Fatty acids, total saturated_g` = NA_real_,
    `Fatty acids, total trans_g` = NA_real_, 
    `Fatty acids, total polyunsaturated_g` = NA_real_, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = NA_real_,
    `Sodium, Na_mg` = NA_real_,
    `Carbohydrate, by difference_g` = NA_real_,
    `Sugars, total_g` = NA_real_,
     Protein_g = NA_real_,
    `Vitamin A, IU_IU` = NA_real_,
    `Vitamin A, RAE_mcg` = NA_real_,
     `Vitamin C, total ascorbic acid_mg` = NA_real_,
     `Vitamin B-12, added_mcg` = NA_real_,  
     `Vitamin D_IU` = NA_real_, 
    `Vitamin D (D2 + D3)_mcg` = NA_real_,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_,
     `Vitamin E (alpha-tocopherol)_mg` = NA_real_, 
    `Vitamin E, added_mg` = NA_real_,
     `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    `Calcium, Ca_mg` = NA_real_,
     `Iron, Fe_mg` =NA_real_,
     Thiamin_mg = NA_real_,
     Riboflavin_mg = NA_real_,
     `Vitamin B-6_mg` = NA_real_,
     `Folate, total_mcg` = NA_real_,
     `Phosphorus, P_mg` = NA_real_,
     `Magnesium, Mg_mg` = NA_real_,
     `Zinc, Zn_mg` = NA_real_,
     `Manganese, Mn_mg` = NA_real_,
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
    `Fiber, total dietary_g` = 3/30*100,
    `Fluoride, F_mcg` = NA_real_, 
    `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_, Niacin_mg = NA_real_, `Pantothenic acid_mg` = NA_real_, 
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, `Potassium, K_mg` = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
    `Selenium, Se_mcg` = NA_real_, Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  `Vitamin B-12_mcg` = NA_real_, 
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Chromium_mcg = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_
     ), class = c("list", "food"))

print.food <- function(x,...) {
  print(do.call("rbind",x[!unlist(lapply(x,is.na))]))
 class(blank.food) <- c("list","food")
}
```

## New foods
```{r ChiaSeeds}
tmp <- blank.food
tmp$Long_Desc <- "Organic Chia Seeds NATURE'S INTENT"
tmp$Price <- 13.99/9.07
tmp$kcal_kcal <- 150/30*100
tmp["Total lipid (fat)_g"] <- 9/30*100
tmp["Fatty acids, total saturated_g"] <- 1/30*100
tmp["Cholesterol_mg"] <- 0
tmp["Sodium, Na_mg"] <- 5/30*100
tmp["Carbohydrate, by difference_g"] <- 2/30*100
tmp["Fiber, total dietary_g"] <- 11/30*100
tmp["Protein_g"] <- 5/30*100
tmp["Vitamin A, IU_IU"] <- 0
tmp["Vitamin A, RAE_mcg"] <- 0
tmp["Vitamin C, total ascorbic acid_mg"] <- 0
tmp["Calcium, Ca_mg"] <- dv2mg_Ca(20/30*100)
tmp["Iron, Fe_mg"] <- dv2mg_Fe(15/30*100)
tmp["Potassium, K_mg"] <- 160 #http://nutritiondata.self.com/facts/nut-and-seed-products/3061/2
names(tmp)[names(tmp) %!in% names(USDAwide)]
names(tmp) <- gsub("Âµ","µ",names(tmp))
organic.chia.seeds.NATURES.INTENT <- tmp
USDAwide <- rbind(USDAwide,organic.chia.seeds.NATURES.INTENT,use.names=TRUE)
```

```{r HempHearts}
# $6.74
hemp.hearts <- structure(list(
     Long_Desc = "Hemp Hearts, Raw shelled hemp seeds, MANITOBA HARVEST",
     Price = 14.89/26/30*100,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = 170/30*100,
    `Total lipid (fat)_g` = 13/30*100,
    `Fatty acids, total saturated_g` = 1.5/30*100,
    `Fatty acids, total trans_g` = 0, 
    `Fatty acids, total polyunsaturated_g` = 10/30*100, 
    `Fatty acids, total monounsaturated_g` = 1.5/30*100, 
    Cholesterol_mg = 0,
    `Sodium, Na_mg` = 0, 
    `Carbohydrate, by difference_g` = .5/30*100, #less than 1g
    `Sugars, total_g` = .5/30*100, #less than 1g; estimated more online at 3.6g
     Protein_g = 10/30*100,
    `Vitamin A, IU_IU` = 0, 
    `Vitamin A, RAE_mcg` = 0,
     `Vitamin C, total ascorbic acid_mg` = 0,
    `Calcium, Ca_mg` = dv2mg_Ca(2)/30*100, 
     `Iron, Fe_mg` = dv2mg_Fe(20),
     Thiamin_mg = dv2mg_Thiamin(25),
     Riboflavin_mg = dv2mg_Riboflavin(6),
     `Vitamin B-6_mg` = dv2mg_B6(8),
     `Folate, total_mcg` = DRI2unit(8,"Folate, total_mcg"),
     `Phosphorus, P_mg` = dv2mg_P(45),
     `Magnesium, Mg_mg` = dv2mg_Magnesium(45), 
     `Zinc, Zn_mg` = dv2mg_Zn(20),
     `Manganese, Mn_mg` = dv2mg_Manganese(110),
     `Potassium, K_mg` = mean(c(
       (360/30)*100, #http://www.nowfoods.com/Organic-Hemp-Seed-Hearts-8-oz.htm
       (633/56)*100 #http://www.hempseed.ca/hulled-hemp-seed.ihtml
     )),
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 

    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
    `Fiber, total dietary_g` = 3/30*100,
    `Fluoride, F_mcg` = NA_real_, 
    `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_, Niacin_mg = NA_real_, `Pantothenic acid_mg` = NA_real_, 
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
    `Selenium, Se_mcg` = NA_real_, Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  `Vitamin B-12_mcg` = NA_real_, 
    `Vitamin B-12, added_mcg` = NA_real_,  
     `Vitamin D_IU` = NA_real_, 
    `Vitamin D (D2 + D3)_mcg` = NA_real_, `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_, `Vitamin E (alpha-tocopherol)_mg` = NA_real_, 
    `Vitamin E, added_mg` = NA_real_, `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Chromium_mcg = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))

names(hemp.hearts)[names(hemp.hearts) %!in% names(USDAwide)]
USDAwide <- rbind(USDAwide,hemp.hearts,use.names=TRUE)
```


```{r dailyMulti}
#I can't square mcg and IU for Vitamin D and it is too high in iron anayway
#   kirklandDailyMulti <- structure(list(Long_Desc = "Kirkland Signature Daily Multi", 
#     Price = NA_real_, NDB_No = NA, Refuse = 0, kcal_kcal = NA_real_, 
#     `Total lipid (fat)_g` = NA_real_, `Fatty acids, total saturated_g` = NA_real_, 
#     `Fatty acids, total trans_g` = NA_real_, `Fatty acids, total polyunsaturated_g` = NA_real_, 
#     `Fatty acids, total monounsaturated_g` = NA_real_, Cholesterol_mg = NA_real_, 
#     `Sodium, Na_mg` = NA_real_, `Carbohydrate, by difference_g` = NA_real_, 
#     `Sugars, total_g` = NA_real_, Protein_g = NA_real_, `Vitamin A, IU_IU` = 3500, 
#     `Vitamin A, RAE_mcg` = NA_real_, `Vitamin C, total ascorbic acid_mg` = 90, 
#     `Calcium, Ca_mg` = 200, `Iron, Fe_mg` = 18, Thiamin_mg = 1.5, 
#     Riboflavin_mg = 1.7, `Vitamin B-6_mg` = 2, `Folate, total_mcg` = NA_real_, 
#     `Phosphorus, P_mg` = 109, `Magnesium, Mg_mg` = 100, `Zinc, Zn_mg` = 11, 
#     `Manganese, Mn_mg` = 2.3, `10:0_g` = NA_real_, `12:0_g` = NA_real_, 
#     `13:0_g` = NA_real_, `14:0_g` = NA_real_, `14:1_g` = NA_real_, 
#     `15:0_g` = NA_real_, `15:1_g` = NA_real_, `16:0_g` = NA_real_, 
#     `16:1 c_g` = NA_real_, `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
#     `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
#     `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
#     `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
#     `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
#     `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
#     `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
#     `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
#     `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
#     `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
#     `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
#     `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
#     `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
#     `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
#     `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
#     `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
#     `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
#     Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
#     Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
#     Betaine_mg = NA_real_, Caffeine_mg = NA_real_, Campesterol_mg = NA_real_, 
#     `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
#     `Choline, total_mg` = NA_real_, `Copper, Cu_mg` = 0.9, `Cryptoxanthin, beta_mcg` = NA_real_, 
#     Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
#     `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
#     `Fiber, total dietary_g` = 10, `Fluoride, F_mcg` = NA_real_, 
#     `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
#     `Folic acid_mcg` = 500, Fructose_g = NA_real_, Galactose_g = NA_real_, 
#     `Glucose (dextrose)_g` = NA_real_, `Glutamic acid_g` = NA_real_, 
#     Glycine_g = NA_real_, Histidine_g = NA_real_, Hydroxyproline_g = NA_real_, 
#     Isoleucine_g = NA_real_, Lactose_g = NA_real_, Leucine_g = NA_real_, 
#     `Lutein + zeaxanthin_mcg` = 250, Lycopene_mcg = 300, Lysine_g = NA_real_, 
#     Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, Methionine_g = NA_real_, 
#     Niacin_mg = 20, `Pantothenic acid_mg` = NA_real_, Phenylalanine_g = NA_real_, 
#     Phytosterols_mg = NA_real_, `Potassium, K_mg` = 80, Proline_g = NA_real_, 
#     Retinol_mcg = NA_real_, `Selenium, Se_mcg` = 55, Serine_g = NA_real_, 
#     Starch_g = NA_real_, Stigmasterol_mg = NA_real_, Sucrose_g = NA_real_, 
#     Theobromine_mg = NA_real_, Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
#     `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
#     Tryptophan_g = NA_real_, Tyrosine_g = NA_real_, Valine_g = NA_real_, 
#     `Vitamin B-12_mcg` = 6, `Vitamin B-12, added_mcg` = 6, `Vitamin D_IU` = 400, 
#     `Vitamin D (D2 + D3)_mcg` = 100, `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
#     `Vitamin D3 (cholecalciferol)_mcg` = 10, `Vitamin E (alpha-tocopherol)_mg` = 20, 
#     `Vitamin E, added_mg` = 20, `Vitamin K (phylloquinone)_mcg` = 25, 
#     Water_g = NA_real_, kJ_kJ = NA_real_, Chromium_mcg = NA_real_), class = c("list", "food"))
# 
# names(kirklandDailyMulti)[names(kirklandDailyMulti) %!in% names(USDAwide)]
# USDAwide <- rbind(USDAwide,kirklandDailyMulti,use.names=TRUE)
```

```{r RawMeal}
# $19.85
rawmealProd <- (1/85)*100
rawmeal <- structure(list(
     Long_Desc = "RawMeal",
     Price = 37.53/((14*85)/100),
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = 270/85*100,
    `Total lipid (fat)_g` = 2.5/85*100,
    `Fatty acids, total saturated_g` = 0,
    `Fatty acids, total trans_g` = NA_real_, 
    `Fatty acids, total polyunsaturated_g` = 2/85*100, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = 0,
    `Sodium, Na_mg` = 95/85*100,
    `Carbohydrate, by difference_g` = 26/85*100,
     `Fiber, total dietary_g` = 9,
    `Sugars, total_g` = 26/85*100,
     Protein_g = 34/85*100,
    `Vitamin A, IU_IU` = DRI2unit(30,"Vitamin A, IU_IU")*rawmealProd,
    `Vitamin A, RAE_mcg` = NA_real_,
     `Vitamin C, total ascorbic acid_mg` = DRI2unit(100,"Vitamin C, total ascorbic acid_mg")*rawmealProd,
     `Vitamin B-12_mcg` = DRI2unit(200,"Vitamin B-12_mcg")*rawmealProd, 
     `Vitamin B-12, added_mcg` = NA_real_,  
     `Vitamin D_IU` = DRI2unit(100,"Vitamin D_IU")*rawmealProd, 
    `Vitamin D (D2 + D3)_mcg` = DRI2unit(100,"Vitamin D (D2 + D3)_mcg")*rawmealProd,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_,
     `Vitamin E (alpha-tocopherol)_mg` = DRI2unit(100,"Vitamin E (alpha-tocopherol)_mg")*rawmealProd, 
    `Vitamin E, added_mg` = NA_real_,
     `Vitamin K (phylloquinone)_mcg` = DRI2unit(100,"Vitamin K (phylloquinone)_mcg")*rawmealProd, 
    `Calcium, Ca_mg` = DRI2unit(35,"Calcium, Ca_mg")*rawmealProd,
     `Iron, Fe_mg` =DRI2unit(100,"Iron, Fe_mg")*rawmealProd,
     Thiamin_mg = DRI2unit(100,"Thiamin_mg")*rawmealProd,
     Riboflavin_mg = DRI2unit(100,"Riboflavin_mg")*rawmealProd,
     Niacin_mg = DRI2unit(100,"Niacin_mg")*rawmealProd,
     `Vitamin B-6_mg` = DRI2unit(100,"Vitamin B-6_mg")*rawmealProd,
     `Folate, total_mcg` = DRI2unit(100,"Folate, total_mcg")*rawmealProd,
     `Phosphorus, P_mg` = NA_real_,
     `Magnesium, Mg_mg` = DRI2unit(31,"Magnesium, Mg_mg")*rawmealProd,
     `Zinc, Zn_mg` = DRI2unit(100,"Zinc, Zn_mg")*rawmealProd,
     `Selenium, Se_mcg` = DRI2unit(15,"Selenium, Se_mcg")*rawmealProd,
     `Manganese, Mn_mg` = DRI2unit(100,"Manganese, Mn_mg")*rawmealProd,
     Chromium_mcg = DRI2unit(100,"Chromium")*rawmealProd,
     `Potassium, K_mg` = 360*rawmealProd, 
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
  
     `Folate, DFE_mcg` = NA_real_,
     `Folate, food_mcg` = NA_real_, 
     
     
    `Fluoride, F_mcg` = NA_real_, 
     
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_,  `Pantothenic acid_mg` = DRI2unit(100,"Pantothenic acid_mg")*rawmealProd, 
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, 
     
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
     Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))
names(rawmeal)[names(rawmeal) %!in% names(USDAwide)]
USDAwide <- rbind(USDAwide,rawmeal,use.names=TRUE)
```

```{r UltimateMeal}
#$24.48
Prod <- (1/40)*100
ultimatemeal <- structure(list(
     Long_Desc = "UltimateMeal",
    Price = (62.42/1200)*100,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = 170*Prod,
    `Total lipid (fat)_g` = 5*Prod,
    `Fatty acids, total saturated_g` = 0,
    `Fatty acids, total trans_g` = NA_real_, 
    `Fatty acids, total polyunsaturated_g` = 3*Prod, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = NA_real_,
    `Sodium, Na_mg` = 30*Prod,
    `Carbohydrate, by difference_g` = 11*Prod,
     `Fiber, total dietary_g` = 6*Prod,
    `Sugars, total_g` = NA_real_,
     Protein_g = 15*Prod,
    `Vitamin A, IU_IU` = 5500*Prod,
    `Vitamin A, RAE_mcg` = 275*Prod,
     `Vitamin C, total ascorbic acid_mg` = NA_real_,
     `Vitamin B-12_mcg` = 75*Prod, 
     `Vitamin B-12, added_mcg` = NA_real_,  
     `Vitamin D_IU` = NA_real_, 
    `Vitamin D (D2 + D3)_mcg` = NA_real_,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_,
     `Vitamin E (alpha-tocopherol)_mg` = NA_real_, 
    `Vitamin E, added_mg` = NA_real_,
     `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    `Calcium, Ca_mg` = 250*Prod,
     `Iron, Fe_mg` = 3*Prod,
     Thiamin_mg = NA_real_,
     Riboflavin_mg = NA_real_,
     Niacin_mg = NA_real_,
     `Vitamin B-6_mg` = NA_real_,
     `Folate, total_mcg` = 125*Prod,
     `Phosphorus, P_mg` = NA_real_,
     `Magnesium, Mg_mg` = 125*Prod,
     `Zinc, Zn_mg` = NA_real_,
     `Selenium, Se_mcg` = NA_real_,
     `Manganese, Mn_mg` = NA_real_,
     `Potassium, K_mg` = 160*Prod, 
     Chromium_mcg = NA_real_,
     `Folic acid_mcg` = 125*Prod, 
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
  
     `Folate, DFE_mcg` = NA_real_,
     `Folate, food_mcg` = NA_real_, 
     
     
    `Fluoride, F_mcg` = NA_real_, 
     
     
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_,  `Pantothenic acid_mg` = NA_real_, 
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
     Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))
names(ultimatemeal)[names(ultimatemeal) %!in% names(USDAwide)]
names(USDAwide)[names(USDAwide) %!in% names(ultimatemeal)]
USDAwide <- rbind(USDAwide,ultimatemeal,use.names=TRUE)
```

```{r VitaminASup}
VitaminASup <- structure(list(
     Long_Desc = "VitaminASupRSP",
     Price = 10.99/300,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = NA_real_,
    `Total lipid (fat)_g` = NA_real_,
    `Fatty acids, total saturated_g` = NA_real_,
    `Fatty acids, total trans_g` = NA_real_, 
    `Fatty acids, total polyunsaturated_g` = NA_real_, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = NA_real_,
    `Sodium, Na_mg` = NA_real_,
    `Carbohydrate, by difference_g` = NA_real_,
    `Sugars, total_g` = NA_real_,
     Protein_g = NA_real_,
    `Vitamin A, IU_IU` = 12500,
    `Vitamin A, RAE_mcg` = NA_real_,
     `Vitamin C, total ascorbic acid_mg` = NA_real_,
     `Vitamin B-12, added_mcg` = NA_real_,  
     `Vitamin D_IU` = NA_real_, 
    `Vitamin D (D2 + D3)_mcg` = NA_real_,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_,
     `Vitamin E (alpha-tocopherol)_mg` = NA_real_, 
    `Vitamin E, added_mg` = NA_real_,
     `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    `Calcium, Ca_mg` = NA_real_,
     `Iron, Fe_mg` =NA_real_,
     Thiamin_mg = NA_real_,
     Riboflavin_mg = NA_real_,
     `Vitamin B-6_mg` = NA_real_,
     `Folate, total_mcg` = NA_real_,
     `Phosphorus, P_mg` = NA_real_,
     `Magnesium, Mg_mg` = NA_real_,
     `Zinc, Zn_mg` = NA_real_,
     `Manganese, Mn_mg` = NA_real_,
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
    `Fiber, total dietary_g` = 3/30*100,
    `Fluoride, F_mcg` = NA_real_, 
    `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_, Niacin_mg = NA_real_, `Pantothenic acid_mg` = NA_real_, 
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, `Potassium, K_mg` = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
    `Selenium, Se_mcg` = NA_real_, Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  `Vitamin B-12_mcg` = NA_real_, 
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Chromium_mcg = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))
USDAwide <- rbind(USDAwide,VitaminASup,use.names=TRUE)
```


```{r VitaminDSup}
VitaminDSup <- structure(list(
     Long_Desc = "VitaminDSupRSP",
     Price = 12.05/360,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = NA_real_,
    `Total lipid (fat)_g` = NA_real_,
    `Fatty acids, total saturated_g` = NA_real_,
    `Fatty acids, total trans_g` = NA_real_, 
    `Fatty acids, total polyunsaturated_g` = NA_real_, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = NA_real_,
    `Sodium, Na_mg` = NA_real_,
    `Carbohydrate, by difference_g` = NA_real_,
    `Sugars, total_g` = NA_real_,
     Protein_g = NA_real_,
    `Vitamin A, IU_IU` = NA_real_,
    `Vitamin A, RAE_mcg` = NA_real_,
     `Vitamin C, total ascorbic acid_mg` = NA_real_,
     `Vitamin B-12, added_mcg` = NA_real_,  
     `Vitamin D_IU` = 2000, 
    `Vitamin D (D2 + D3)_mcg` = 50,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = 50,
     `Vitamin E (alpha-tocopherol)_mg` = NA_real_, 
    `Vitamin E, added_mg` = NA_real_,
     `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    `Calcium, Ca_mg` = NA_real_,
     `Iron, Fe_mg` =NA_real_,
     Thiamin_mg = NA_real_,
     Riboflavin_mg = NA_real_,
     `Vitamin B-6_mg` = NA_real_,
     `Folate, total_mcg` = NA_real_,
     `Phosphorus, P_mg` = NA_real_,
     `Magnesium, Mg_mg` = NA_real_,
     `Zinc, Zn_mg` = NA_real_,
     `Manganese, Mn_mg` = NA_real_,
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
    `Fiber, total dietary_g` = 3/30*100,
    `Fluoride, F_mcg` = NA_real_, 
    `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_, Niacin_mg = NA_real_, `Pantothenic acid_mg` = NA_real_, 
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, `Potassium, K_mg` = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
    `Selenium, Se_mcg` = NA_real_, Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  `Vitamin B-12_mcg` = NA_real_, 
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Chromium_mcg = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))
USDAwide <- rbind(USDAwide,VitaminDSup,use.names=TRUE)
```

```{r ZoneFG}
ZoneFG <- structure(list(
     Long_Desc = "ZoneFG",
     Price = NA,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = 210,
    `Total lipid (fat)_g` = 7,
    `Fatty acids, total saturated_g` = 3.5,
    `Fatty acids, total trans_g` = 0, 
    `Fatty acids, total polyunsaturated_g` = NA_real_, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = 5,
    `Sodium, Na_mg` = 200,
     `Potassium, K_mg` = 90, 
    `Carbohydrate, by difference_g` = 20,
    `Sugars, total_g` = 15,
     Protein_g = 14,
    `Vitamin A, IU_IU` = DRI2unit(35,"Vitamin A, IU_IU"),
    `Vitamin A, RAE_mcg` = NA_real_,
     `Vitamin C, total ascorbic acid_mg` = DRI2unit(50,"Vitamin C, total ascorbic acid_mg"),
     `Calcium, Ca_mg` = DRI2unit(20,"Calcium, Ca_mg"),
     `Iron, Fe_mg` = DRI2unit(10,"Iron, Fe_mg"),
     `Vitamin E (alpha-tocopherol)_mg` = DRI2unit(100,"Vitamin E (alpha-tocopherol)_mg"), 
    `Vitamin E, added_mg` = DRI2unit(100,"Vitamin E, added_mg"),
     Thiamin_mg = DRI2unit(25,"Thiamin_mg"),
     Riboflavin_mg = DRI2unit(50,"Riboflavin"),
     Niacin_mg = DRI2unit(45,"Niacin_mg"),
     `Vitamin B-6_mg` = DRI2unit(50,"Vitamin B-6_mg"),
     `Folate, total_mcg` = DRI2unit(20,"Folate, total_mcg"),
     `Vitamin B-12, added_mcg` = DRI2unit(35,"Vitamin B-12, added_mcg"),  
     #Biotin 25, made in body not worried about
     `Pantothenic acid_mg` = DRI2unit(25,"Panothenic acid_mg"), 
      `Phosphorus, P_mg` = DRI2unit(20,"Phosophorus, P_mg"),
      `Magnesium, Mg_mg` = DRI2unit(10,"Magnesium, Mg_mg"),
     `Zinc, Zn_mg` = DRI2unit(25,"Zinc, Zn_mg"),
     `Manganese, Mn_mg` = NA_real_,
    `Selenium, Se_mcg` = DRI2unit(30,"Selenium, Se_mcg"), 
     Chromium_mcg = DRI2unit(35,"Chromium_mcg"),
     #Molybdenum 35%
     `Vitamin D_IU` = NA_real_, 
    `Vitamin D (D2 + D3)_mcg` = NA_real_,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_,
     
     `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    
     
     
    
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
    `Fiber, total dietary_g` = 3/30*100,
    `Fluoride, F_mcg` = NA_real_, 
    `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_,  
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
    Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  `Vitamin B-12_mcg` = NA_real_, 
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))
USDAwide <- rbind(USDAwide,ZoneFG,use.names=TRUE)
```

```{r Whey100}
Prod <- (1/36.3)*100
Whey100 <- structure(list(
     Long_Desc = "Whey100",
     Price = 45.99/75*Prod,
     NDB_No = NA, Refuse = 0L, 
     kcal_kcal = 140*Prod,
    `Total lipid (fat)_g` = 2.5*Prod,
    `Fatty acids, total saturated_g` = 1.5*Prod,
    `Fatty acids, total trans_g` = 0, 
    `Fatty acids, total polyunsaturated_g` = NA_real_, 
    `Fatty acids, total monounsaturated_g` = NA_real_,
    Cholesterol_mg = 70*Prod,
    `Sodium, Na_mg` = 170*Prod,
     `Potassium, K_mg` = 220*Prod, 
    `Carbohydrate, by difference_g` = 3*Prod,
     `Fiber, total dietary_g` = NA_real_,
    `Sugars, total_g` = 3*Prod,
     Protein_g = 27*Prod,
    `Vitamin A, IU_IU` = NA_real_,
    `Vitamin A, RAE_mcg` = NA_real_,
     `Vitamin C, total ascorbic acid_mg` = NA_real_,
     `Calcium, Ca_mg` = DRI2unit(10,"Calcium, Ca_mg")*Prod,
     `Iron, Fe_mg` = DRI2unit(2,"Iron, Fe_mg")*Prod,
     `Vitamin E (alpha-tocopherol)_mg` = NA_real_, 
    `Vitamin E, added_mg` = NA_real_,
     Thiamin_mg = NA_real_,
     Riboflavin_mg = NA_real_,
     Niacin_mg = NA_real_,
     `Vitamin B-6_mg` = NA_real_,
     `Folate, total_mcg` = NA_real_,
     `Vitamin B-12, added_mcg` = NA_real_,  
     #Biotin 25, made in body not worried about
     `Pantothenic acid_mg` = NA_real_, 
      `Phosphorus, P_mg` = DRI2unit(8,"Phosophorus, P_mg")*Prod,
      `Magnesium, Mg_mg` = DRI2unit(4,"Magnesium, Mg_mg")*Prod,
     `Zinc, Zn_mg` = NA_real_,
     `Manganese, Mn_mg` = NA_real_,
    `Selenium, Se_mcg` = NA_real_, 
     Chromium_mcg = NA_real_,
     #Molybdenum 35%
     `Vitamin D_IU` = NA_real_, 
    `Vitamin D (D2 + D3)_mcg` = NA_real_,
     `Vitamin D2 (ergocalciferol)_mcg` = NA_real_, 
    `Vitamin D3 (cholecalciferol)_mcg` = NA_real_,
     
     `Vitamin K (phylloquinone)_mcg` = NA_real_, 
    
     
     
    
    `10:0_g` = NA_real_, `12:0_g` = NA_real_, `13:0_g` = NA_real_, 
    `14:0_g` = NA_real_, `14:1_g` = NA_real_, `15:0_g` = NA_real_, 
    `15:1_g` = NA_real_, `16:0_g` = NA_real_, `16:1 c_g` = NA_real_, 
    `16:1 t_g` = NA_real_, `16:1 undifferentiated_g` = NA_real_, 
    `17:0_g` = NA_real_, `17:1_g` = NA_real_, `18:0_g` = NA_real_, 
    `18:1-11t (18:1t n-7)_g` = NA_real_, `18:1 c_g` = NA_real_, 
    `18:1 t_g` = NA_real_, `18:1 undifferentiated_g` = NA_real_, 
    `18:2 CLAs_g` = NA_real_, `18:2 i_g` = NA_real_, `18:2 n-6 c,c_g` = NA_real_, 
    `18:2 t not further defined_g` = NA_real_, `18:2 t,t_g` = NA_real_, 
    `18:2 undifferentiated_g` = NA_real_, `18:3 n-3 c,c,c (ALA)_g` = NA_real_, 
    `18:3 n-6 c,c,c_g` = NA_real_, `18:3 undifferentiated_g` = NA_real_, 
    `18:3i_g` = NA_real_, `18:4_g` = NA_real_, `20:0_g` = NA_real_, 
    `20:1_g` = NA_real_, `20:2 n-6 c,c_g` = NA_real_, `20:3 n-3_g` = NA_real_, 
    `20:3 n-6_g` = NA_real_, `20:3 undifferentiated_g` = NA_real_, 
    `20:4 n-6_g` = NA_real_, `20:4 undifferentiated_g` = NA_real_, 
    `20:5 n-3 (EPA)_g` = NA_real_, `21:5_g` = NA_real_, `22:0_g` = NA_real_, 
    `22:1 c_g` = NA_real_, `22:1 t_g` = NA_real_, `22:1 undifferentiated_g` = NA_real_, 
    `22:4_g` = NA_real_, `22:5 n-3 (DPA)_g` = NA_real_, `22:6 n-3 (DHA)_g` = NA_real_, 
    `24:0_g` = NA_real_, `24:1 c_g` = NA_real_, `4:0_g` = NA_real_, 
    `6:0_g` = NA_real_, `8:0_g` = NA_real_, `Adjusted Protein_g` = NA_real_, 
    Alanine_g = NA_real_, `Alcohol, ethyl_g` = NA_real_, Arginine_g = NA_real_, 
    Ash_g = NA_real_, `Aspartic acid_g` = NA_real_, `Beta-sitosterol_mg` = NA_real_, 
    Betaine_mg = NA_real_, Caffeine_mg = NA_real_, 
    Campesterol_mg = NA_real_, 
    `Carotene, alpha_mcg` = NA_real_, `Carotene, beta_mcg` = NA_real_, 
    `Choline, total_mg` = NA_real_, 
    `Copper, Cu_mg` = NA_real_, `Cryptoxanthin, beta_mcg` = NA_real_, 
    Cystine_g = NA_real_, Dihydrophylloquinone_mcg = NA_real_, 
    `Fatty acids, total trans-monoenoic_g` = NA_real_, `Fatty acids, total trans-polyenoic_g` = NA_real_, 
    
    `Fluoride, F_mcg` = NA_real_, 
    `Folate, DFE_mcg` = NA_real_, `Folate, food_mcg` = NA_real_, 
     `Folic acid_mcg` = NA_real_, 
    Fructose_g = NA_real_, Galactose_g = NA_real_, `Glucose (dextrose)_g` = NA_real_, 
    `Glutamic acid_g` = NA_real_, Glycine_g = NA_real_, Histidine_g = NA_real_, 
    Hydroxyproline_g = NA_real_,  Isoleucine_g = NA_real_, 
    Lactose_g = NA_real_, Leucine_g = NA_real_, `Lutein + zeaxanthin_mcg` = NA_real_, 
    Lycopene_mcg = NA_real_, Lysine_g = NA_real_, 
    Maltose_g = NA_real_, `Menaquinone-4_mcg` = NA_real_, 
    Methionine_g = NA_real_,  
    Phenylalanine_g = NA_real_,  
    Phytosterols_mg = NA_real_, 
    Proline_g = NA_real_, Retinol_mcg = NA_real_, 
    Serine_g = NA_real_, 
    Starch_g = NA_real_, Stigmasterol_mg = NA_real_, 
    Sucrose_g = NA_real_, Theobromine_mg = NA_real_, 
     Threonine_g = NA_real_, `Tocopherol, beta_mg` = NA_real_, 
    `Tocopherol, delta_mg` = NA_real_, `Tocopherol, gamma_mg` = NA_real_, 
    Tryptophan_g = NA_real_, 
    Tyrosine_g = NA_real_, Valine_g = NA_real_,  `Vitamin B-12_mcg` = NA_real_, 
    Water_g = NA_real_,  
    kJ_kJ = NA_real_, Biotin_mcg=NA_real_,Iodine_mcg=NA_real_), class = c("list", "food"))
USDAwide <- rbind(USDAwide,Whey100,use.names=TRUE)
```